name: Deploy
run-name: Deploy workflow invoked by ${{ github.actor }}

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install surge
        run: apt-get install surge
      - name: Deploy application
        run: surge source/ --domain https://pspiess.surge.sh
