name: Deploy
run-name: Deploy workflow invoked by ${{ github.actor }}

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install surge
        run: sudo npm install --global surge
      - name: Deploy application
        run: surge source/ --domain https://pspiess.surge.sh
