name: Deploy
run-name: Deploy workflow invoked by ${{ github.actor }}

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      SURGE_LOGIN: ${{ vars.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install surge
        run: sudo npm install --global surge
      - name: Deploy application
        run: |
          echo "Publishing as $SURGE_LOGIN"
          surge source/ --domain https://pspiess.surge.sh
